# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: nginx-confd-nacos CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  container-job:
    env:
      NginxUtilTestCMD: nginx -c /tmp/http.conf -p /tmp

    runs-on: ubuntu-latest

    services:
      nacos:
        image: nacos/nacos-server:2.0.2
        env:
          MODE: standalone
        ports:
          - 8848:8848

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Copy Nginx Config file
      run: |
        cp src/test/resources/http.conf /tmp/ \
        && touch /tmp/server.location \
        && touch /tmp/nacos.upstream \
    - name: Nginx Test
      run: ${NginxUtilTestCMD} -T
    - name: Nginx Start
      run: ${NginxUtilTestCMD}
    - name: Nginx Curl
      run: curl -I http://127.0.0.1:3000
    - name: Nginx Reload
      run: ${NginxUtilTestCMD} -s reload
    - name: Test
      run: mvn test
    - name: Nacos Test
      run: curl http://127.0.0.1:8848/nacos/v1/
