# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: nginx-confd-nacos CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    env:
      NginxUtilTestCMD: nginx -c /tmp/http.conf -p /tmp
      ncn.delay: 1
      ncn.period: 1
      ncn.conf.upstream: /tmp/nacos.upstream
      ncn.conf.location: /tmp/server.location


    runs-on: ubuntu-latest

    services:
      nacos:
        image: nacos/nacos-server:2.0.2
        env:
          MODE: standalone
        ports:
          - 8848:8848
        options: >-
          --health-cmd "curl -f http://127.0.0.1:8848/nacos/actuator/health"
          --health-interval 10s
          --health-timeout 1s
          --health-retries 10
          --health-start-period 30s

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Copy Nginx Config file
      run: |
        cp src/test/resources/http.conf /tmp/ \
        && touch /tmp/server.location \
        && touch /tmp/nacos.upstream \
    - name: Nginx Test
      run: ${NginxUtilTestCMD} -T
    - name: Nginx Start
      run: ${NginxUtilTestCMD}
    - name: Nginx Curl
      run: curl -I http://127.0.0.1:3000
    - name: Nginx Reload
      run: ${NginxUtilTestCMD} -s reload
    - name: Nacos Test
      run: curl -f http://127.0.0.1:8848/nacos/actuator/health
    - name: Sleep for Nacos
      run: sleep 60
    - name: Test
      run: mvn -B test
