# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: nginx-confd-nacos CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Copy Nginx Config file
      run: |
        cp src/test/resources/http.conf /tmp/ \
        && touch /tmp/server.location \
        && touch /tmp/nacos.upstream \
    - name: Nginx Test
      run: nginx -c /tmp/http.conf -T
    - name: Nginx Start
      run: nginx -c /tmp/http.conf
    - name: Nginx Curl
      run: curl -I http://127.0.0.1:3000
    - name: Nginx Reload
      run: nginx -c /tmp/http.conf -s reload

